volumes: #create USB drives
  overrated:
    external: true
  pg-admin:
    external: true
services: # Container that we want to run
  api: # have to run docker-compose build
    build:
      context: api # name of the directory
      dockerfile: Dockerfile.dev # name of the dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      PGHOST: db
      PGDATABASE: overrated
      PGUSER: overrated
      PGPASSWORD: overrated
  db: # not sure about db directories 
    build: 
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - overrated:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: overrated
      POSTGRES_USER: overrated
      POSTGRES_DB: overrated
    ports: 
      - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4 #I only have to bat-man up
    volumes: 
      - pg-admin:/var/lib/pgadmin4
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@overrated.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
