volumes: #create USB drives
  overrated:
    external: true
  pg-admin:
    external: true
services: # Container that we want to run
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
  profiles_api: # have to run docker-compose build
    build:
      context: profiles_api # name of the directory
      dockerfile: Dockerfile.dev # name of the dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./profiles_api:/app
    environment:
      DATABASE_URL: postgresql://overrated:overrated@postgres/overrated
      SECRET_KEY: 10a62668ff6b1fc0ac7ea61128a50c997748d21d7926b6b2a7fe870c9f9b7d46
      AWS_SERVER_PUBLIC_KEY: ${AWS_SERVER_PUBLIC_KEY}
      AWS_SERVER_SECRET_KEY: ${AWS_SERVER_SECRET_KEY}
  postgres:
    image: postgres:14-bullseye
    ports:
      - "15432:5432"
    volumes:
      # For your initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      # For the data stored by PostgreSQL
      - overrated:/var/lib/postgresql/data
    environment:
      # Password for the postgres superuser
      #   for the user of the application database
      POSTGRES_PASSWORD: secret
  # db: # not sure about db directories
  #   build:
  #     context: data
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - overrated:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: overrated
  #     POSTGRES_USER: overrated
  #     POSTGRES_DB: overrated
  #   ports:
  #     - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4 #I only have to docker-compose up
    volumes:
      - pg-admin:/var/lib/pgadmin4
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@overrated.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
